swagger: "2.0"
info:
  title: ""
  version: ""
  x-java-interface: "com.xxx.order.Data"
basePath: /
paths:
  /price/{id}:
    get:
      operationId: GetPrice
      parameters:
      - name: x-auth-token
        in: header
        description: this is a token
        type: string
      - name: x-auth-token2
        in: header
        description: this is a token
        type: string
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      responses:
        "200":
          description: "true"
          schema:
            $ref: '#/definitions/Data'
definitions:
  Data:
    type: object
    properties:
      priceID:
        type: string
      type:
        type: string
      value:
        type: string
